### ISSUE TITLE
remove /server_api proxy, It's doesn't work!

### ISSUE THREAD

**Issue by SiegfriedUK** [ecomfe/basr#1]
I want change the edp webserver to express, so I was removed '/server_api' proxy, and change the url to 'http://vop.baidu.com/server_api', but It doesn't work...

console throwError: 

> XMLHttpRequest cannot load http://vop.baidu.com/server_api. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8848' is therefore not allowed access.
> index.html:73 Error: {"type":"unknow"}(anonymous function) @ index.html:73

**Comment by treelite** [comment]
The RESTful API (http://vop.baidu.com/server_api) didn't support across-domain access yet, so it will work fine if you use Express to make a proxy API for it just like the demo.
